### PR TITLE
New Data.

### PR DESCRIPTION
**Pull request by connor-mcisaac**
I have added in new files using O1 data and reoranised these slightly.
There is now a bank of noise files, in that folder there are also glitches that could be used later.
The signal bank is organised in much the same way, I will at some point add the signals in glitchy noise.
the signalBank json file has changed slightly, it now holds spin information as well, it has information on the number of each type of file and a few variable that are part of how the data generation functions.
A new element has been added to the html and css files to display the spin, this could probablt be done in a more intuitive way.
The coffee file has been changed so that the signals and noise files are selected from the full list using the metadata in the json file, this saves changing it any time the data files change.
The convert-to-ini file was changed so that empty entries are added to the locs json file for any that exist in one language but not another, and the missing entries are printed when it is run. This was done as it seemed to cause some strange issues when this was not done. (this bit of code could be a bit neater)

### CODE REVIEW

**Comment by Galadirith** [comment]
@connor-mcisaac Thank you so much for such a complete update to all the data. I've started this up locally and the new sound files sound absolutely fantastic 🔉 👍

I've taken an initially look at your code changes and they all look reasonable to me. If you don't mind I will hold off merging until I can take a better look which I will hopefully get to this weekend.

You said that

> The convert-to-ini file was changed so that empty entries are added to the locs json file for any that exist in one language but not another, and the missing entries are printed when it is run. This was done as it seemed to cause some strange issues when this was not done.

Looking at the changes I would guess that the main issue here was with the added `spin-text` field that was missing for the other localisations prompting use of *empty entries*. In the absence of a correct localisation for a particular field it might be better to fall back to the `en` localisation entry value so that something is displayed instead of nothing. What do you think?

I'll try to get back to you as soon as possible with any issue I see, and hopefully we can merge everything in very shortly 😊

**Comment by Galadirith** [comment]
@connor-mcisaac If you would like add any information to the README or parts of the website about how the data has been generated please do add it. Perhaps you would like to keep all of that separate. However I want you to have the option to highlight your great work on these changes.

**Comment by connor-mcisaac** [comment]
@Galadirith I'm glad you like the changes.
I agree that having a default value is better, I have added a change so it defaults to English and only leaves it blank if that is also empty.

I plan on tidying up the data generation code a little and moving it into a public github repository. Once I have done that I will link it in the README.

**Comment by Galadirith** [comment]
@connor-mcisaac Thanks so much for change. Playing through a couple of non-english localisations this makes sense.

> I plan on tidying up the data generation code a little and moving it into a public github repository. Once I have done that I will link it in the README.

Great to know 👍 

Thank you once again for all your hard work on this. The data all sounds fantastic, and it's wonderful to have actual data users are listening to. I've looked through everything and no problems with changes. Very happy to merge this in.

**Pull request merged**
